### ISSUE TITLE
Error during example run "UnboundLocalError: local variable 'lowest_annotation_y' referenced before assignment"

### ISSUE THREAD

**Issue by spleonard1** [barricklab/cryptkeeper#4]
Fresh install, followed quick start instructions creating a new conda environment and running the example, errored out during plot preparation it looks like.

git clone https://github.com/barricklab/cryptkeeper
cd cryptkeeper/
conda env create -f environment.yml
conda activate cryptkeeper
pip install ./
cryptkeeper -h
cd examples/BPMV/
cryptkeeper -i pSMART-LCKan-BPMV1.fna -o output/pSMART-LCKan-BPMV1 -j 8 -c
(cryptkeeper) houtx11:BPMV leonard28$ cryptkeeper -i pSMART-LCKan-BPMV1.fna -o output/pSMART-LCKan-BPMV1 -j 8 -
c
[2024-07-10 11:22:10,080] Cryptkeeper: Running RhoTermPredict
[2024-07-10 11:22:11,419] Cryptkeeper: Running RIT_predict_TransTerm
[2024-07-10 11:22:12,103] Cryptkeeper: Running TSS_predict_promoter_calculator
[2024-07-10 11:25:31,252] Cryptkeeper: Running ORF prediction
[2024-07-10 11:25:31,488] Cryptkeeper: Running RBS prediction
[2024-07-10 11:25:40,960] Cryptkeeper: Exporting data
Traceback (most recent call last):
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/bin/cryptkeeper", line 8, in <module>
    sys.exit(main())
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/cryptkeeper.py", line 126, in main
    _ = make_plot(
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/plot.py", line 401, in make_plot
    reverse_height = lowest_annotation_y - 500
UnboundLocalError: local variable 'lowest_annotation_y' referenced before assignment

on Mac:
Darwin houtx11 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64

(cryptkeeper) houtx11:BPMV leonard28$ conda list
# packages in environment at /Users/leonard28/miniconda3/envs/cryptkeeper:
#
# Name                    Version                   Build  Channel
attrs                     23.2.0                   pypi_0    pypi
bio                       1.6.2                    pypi_0    pypi
biopython                 1.84                     pypi_0    pypi
biothings-client          0.3.1                    pypi_0    pypi
bokeh                     3.4.2                    pypi_0    pypi
bzip2                     1.0.8                h10d778d_5    conda-forge
ca-certificates           2024.7.4             h8857fd0_0    conda-forge
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cryptkeeper               0.1                      pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
firefox                   127.0.2              hf036a51_0    conda-forge
geckodriver               0.34.0               h8963483_0    conda-forge
gprofiler-official        1.0.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
libblas                   3.9.0           22_osx64_openblas    conda-forge
libcblas                  3.9.0           22_osx64_openblas    conda-forge
libcxx                    18.1.8               hef8daea_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
liblapack                 3.9.0           22_osx64_openblas    conda-forge
libopenblas               0.3.27          openmp_h8869122_1    conda-forge
libsqlite                 3.46.0               h1b8f9f3_0    conda-forge
libzlib                   1.2.13               h87427d6_6    conda-forge
llvm-openmp               18.1.8               h15ab845_0    conda-forge
markupsafe                2.1.5                    pypi_0    pypi
mygene                    3.2.2                    pypi_0    pypi
ncurses                   6.5                  h5846eda_0    conda-forge
numpy                     2.0.0            py39h3fadf17_0    conda-forge
openssl                   3.3.1                h87427d6_1    conda-forge
ostir                     1.1.2              pyhdfd78af_0    bioconda
outcome                   1.3.0.post0              pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
promotercalculator        1.2.2                    pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.9.19          h7a9c478_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.32.3                   pypi_0    pypi
rhotermpredict            3.3                      pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
selenium                  4.22.0                   pypi_0    pypi
setuptools                70.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.13               h1abcd95_1    conda-forge
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transtermhp               2.09                          0    bioconda
trio                      0.26.0                   pypi_0    pypi
trio-websocket            0.11.1                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
viennarna                 2.4.18           py39hdeec44c_0    bioconda
websocket-client          1.8.0                    pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
wsproto                   1.2.0                    pypi_0    pypi
xyzservices               2024.6.0                 pypi_0    pypi
xz                        5.2.6                h775f41a_0    conda-forge
zlib                      1.2.13               h87427d6_6    conda-forge

**Comment by croots** [comment]
Hi @spleonard1! Should be fixed with latest commit
